INSERT INTO CATEGORIES(NAME, CREATION_TIMESTAMP, UPDATE_TIMESTAMP)
VALUES('shopping', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());

INSERT INTO CATEGORIES(NAME, CREATION_TIMESTAMP, UPDATE_TIMESTAMP)
VALUES('travelling', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());

INSERT INTO CATEGORIES(NAME, CREATION_TIMESTAMP, UPDATE_TIMESTAMP)
VALUES('house loan', CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());